import type { Metadata } from "next";
import { Montserrat, Oswald, Scheherazade_New } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";

import "./globals.css";

const scheherazade = Scheherazade_New({
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
  variable: "--font-scheherazade",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",         // body + UI
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${scheherazade.variable} antialiased ${montserrat.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
        >
          <SidebarProvider defaultOpen={false}>
            {children}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
