import { TopBar } from "@/components/layout/topbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <>
        <TopBar />
        <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
          {children}
        </div>
     </>
  );
}
